---
paths:
    contigs:   contigs
    orfs:      phanotate
    blast:     blast
    databases: /home3/redwards/phage/Sequencing/databases
    statistics: stats

databases:
    phage_proteins: phages.faa
    nr: /home2/db/blast/nr/nr
